### ISSUE TITLE
Permissionless pooling

### ISSUE THREAD

**Issue by kallemoen** [mira-amm/mira-amm-web#94]
Currently, if someone bridges a novel token to the chain or created a fuel native token, there's no way for someone to create their own pool on Mira to trade those tokens. To increase the liquidity and trading activity, we want to add the ability for Mira to work with any tokens. This epic will create a series of changes to the application that help enable that functionality. 

Features to add to application:
- [ ] Liquidity page improvements
- [ ] Permissonless token visibility
- [ ] Generalize "add liqudity" page

**Comment by amaljosea** [comment]
Hi @kallemoen, documenting the "Liquidity page improvements" here https://github.com/mira-amm/mira-amm-web/issues/99.

Please assign https://github.com/mira-amm/mira-amm-web/issues/99 to me.
